# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.random.random((3,3,3,))  #representing rows,columns and channels....

array([[[0.0245316 , 0.02893373, 0.37357822],
        [0.28747064, 0.24078309, 0.83064006],
        [0.19949779, 0.49230137, 0.80135742]],

       [[0.35056737, 0.668819  , 0.57118139],
        [0.7294834 , 0.99431289, 0.97226673],
        [0.98715705, 0.52808147, 0.90250284]],

       [[0.23235805, 0.87508889, 0.09026321],
        [0.75985631, 0.7642637 , 0.29107037],
        [0.69115012, 0.540224  , 0.86835087]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
v=[1,2,3,4]      #creating a matrix with 1,2,3,4 just below the diagonal.................
np.diag(v,-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [11]:

np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [36]:
n=np.zeros((8,8),dtype=int)
n[1::2,::2]=1
n[::2,1::2]=1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [49]:
k=np.random.random((5,5))

kmax,kmin=k.max(),k.min()
k=(k-kmin)/(kmax-kmin)
print(k)

[[0.32846175 1.         0.58264334 0.22083628 0.41396887]
 [0.46421012 0.34953826 0.25090734 0.40931282 0.64305814]
 [0.41958828 0.8345489  0.56969155 0.63423061 0.88613034]
 [0.96995604 0.         0.27464272 0.88379515 0.24449922]
 [0.70061136 0.89998711 0.13563543 0.98243429 0.31223575]]


# 5.  How to find common values between two arrays?

'''to find the common values betwenn two arrays the function is numpy.intersect1d '''

In [74]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([6,7,11,12,13])
np.intersect1d(a,b)

array([6, 7])

In [79]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[2,5,8],[7,6,5]])
print(b)
np.intersect1d(a,b)

[[1 2 3]
 [4 5 6]]
[[2 5 8]
 [7 6 5]]


array([2, 5, 6])

# 6.How to get the dates of yesterday, today and tomorrow?

In [66]:
k=np.datetime64('today','D')
print(k)

2020-07-26


In [71]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(yesterday)
today=np.datetime64('today','D')
print(today)
tommorow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(tommorow)


2020-07-25
2020-07-26
2020-07-27


# 7. Consider two random array A and B, check if they are equal

To check comman values between two arrays the function that can be used is numpy.allclose()

In [72]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
equal=np.allclose(a,b)
print(a)
print(b)
print(equal)

[1 2 3 4 5]
[1 2 3 4 5]
True


In [73]:
f=np.random.random((3,3))
print(f)
g=np.random.random((3,3))
print(g)
equal=np.allclose(f,g)
print(equal)

[[0.59638699 0.47958777 0.95975394]
 [0.99880782 0.96534422 0.9489618 ]
 [0.97671455 0.29641488 0.86329732]]
[[0.44169173 0.9674938  0.11106337]
 [0.92849092 0.26795814 0.1508092 ]
 [0.20240814 0.74798398 0.85059966]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [84]:
z=np.random.random(10)
print(z)
z[z.argmax()]=0
print(z)

[0.77488334 0.73978428 0.61465773 0.9390151  0.37580894 0.64946364
 0.73647925 0.69202527 0.47733809 0.99830576]
[0.77488334 0.73978428 0.61465773 0.9390151  0.37580894 0.64946364
 0.73647925 0.69202527 0.47733809 0.        ]


# 9. How to print all the values of an array?

In [20]:
arr=np.arange(1005)
np.set_printoptions(threshold=np.inf)
print(arr)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

# 10.Subtract the mean of each row of a matrix

In [22]:
x=np.random.rand(5,5)
print(x)
y=x-x.mean(axis=1,keepdims=True)
print(y)


[[0.1313368  0.78465497 0.41966315 0.4458907  0.05993801]
 [0.86998416 0.26950774 0.91180649 0.21720732 0.62162922]
 [0.18206834 0.10457319 0.66251222 0.4236683  0.9156392 ]
 [0.71766732 0.70917398 0.6200037  0.25720465 0.56238313]
 [0.94017473 0.55012461 0.21612307 0.09261821 0.70816397]]
[[-0.23695993  0.41635824  0.05136642  0.07759397 -0.30835871]
 [ 0.29195717 -0.30851924  0.3337795  -0.36081967  0.04360224]
 [-0.27562391 -0.35311906  0.20481997 -0.03402395  0.45794696]
 [ 0.14438077  0.13588742  0.04671714 -0.3160819  -0.01090342]
 [ 0.43873381  0.04868369 -0.28531785 -0.40882271  0.20672305]]


# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [28]:
h=np.random.randint(0,10,40)
print(h)
print(np.bincount(h).argmax())

[3 0 6 7 8 3 7 9 3 8 4 6 2 0 8 7 1 0 8 7 3 8 5 1 5 2 1 4 7 0 1 3 3 7 7 0 8
 9 3 7]
7


# 14.How to get the n largest values of an array

In [39]:
t=np.arange(10)
print(t)
np.random.shuffle(x)
print(t[np.argsort(t)[-1:]])


[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [41]:
w=np.array([1,2,3,4])
e=np.array(['red','blue','pink','orange'])
np.core.records.fromarrays([w,e])

rec.array([(1, 'red'), (2, 'blue'), (3, 'pink'), (4, 'orange')],
          dtype=[('f0', '<i4'), ('f1', '<U6')])